### PR TITLE
default CLI execute in vm

### PR DESCRIPTION
**Pull request by huayang-codaio**
simple change. default CLI execute with vm option.

### CODE REVIEW

**Review by jonathan-codaio — APPROVED** [review]
Exciting.

I assume this works quite reliably now and stack traces are actionable?

**Comment by huayang-codaio** [comment]
> I assume this works quite reliably now and stack traces are actionable?

@jonathan-codaio Except that that path may look weird because the bundle is built in a tmp folder. I spent a some time before but there isn't a easy way to fix it unless 1) we build the bundle in current folder, or 2) patch the source map package...

```
huayang@Huayangs-MBP [14:30:28] [~/code/packs-sdk] [hg-default-vm-execute]
-> % ./node_modules/.bin/ts-node cli/coda.ts execute test/packs/fake.ts Throw           
Error: here
    at throwError (../../../../../../private/var/folders/Users/huayang/code/packs-sdk/test/packs/fake.ts:24:9)
    at Object.execute (../../../../../../private/var/folders/Users/huayang/code/packs-sdk/test/packs/fake.ts:67:9)
    at doFindAndExecutePackFunction (/Users/huayang/code/packs-sdk/bundles/thunk_bundle.js:4796:22)
    at Object.findAndExecutePackFunction (/Users/huayang/code/packs-sdk/bundles/thunk_bundle.js:4786:18)
    at <unknown> (<isolated-vm>:1:13)
```

**Comment by jonathan-codaio** [comment]
Seems non-blocking. Let's go ahead and merge and try it out.

Maybe we can clean up the stack traces but if it's really just path cleanliness that seems more like a backlog item than anything that should block us from starting to use this.

**Comment by huayang-codaio** [comment]
I'll create a backlog item for this in the tech debt section.

**Pull request merged**
