### PR TITLE
Moved READMEs to published doc

### PR DESCRIPTION
**Pull request by punit-codaio**

### CODE REVIEW

**Review by jonathan-codaio — COMMENTED** [review]
Can you try running `make docs`? Not sure if your environment is set up properly for this. The README gets bundled into what shows up at https://coda.github.io/packs-sdk/, so rebuilding will update things there too.

If it doesn't work for you I can just run it after you merge this.

**Comment by punit-codaio** [comment]
oh hmm i don't think i have my dev environment setup enough such that `make docs` just errors out when i try to run. do you mind doing that after i merge?

**Review by jonathan-codaio — APPROVED** [review]
Yeah go for it.

**Comment by punit-codaio** [comment]
super thanks jonathan

**Pull request merged**
