### PR TITLE
make default parameter to work in CLI

### PR DESCRIPTION
**Pull request by huayang-codaio**
https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/Bugs_sucBW#Bugs_tuq-W/r19740&view=modal

before:

```
-> % ./node_modules/.bin/ts-node cli/coda.ts execute test/packs/fake_v2.ts formulaWithOptionalParameter                                   
{ Name: undefined }
```

after:

```
-> % ./node_modules/.bin/ts-node cli/coda.ts execute test/packs/fake_v2.ts formulaWithOptionalParameter
{ Name: 'Bob' }
```

@jonathan-codaio @coda/packs

### CODE REVIEW

**Review by jonathan-codaio — COMMENTED** [review]
I flagged in the bug for @ekoleda-codaio to weigh in on whether this change is actually desirable, given that the "default" value isn't really a default in practice.

**Comment by huayang-codaio** [comment]
oh do we not use default value in optional parameters actually?

**Comment by ekoleda-codaio** [comment]
Copying my note from the bug:

> Ya, I wouldn’t vote for implementing this as described. This does seem like another case where the name defaultValue set wrong expectations. If the parameter was called suggestedValue I doubt people would expect that behavior on the CLI. Does underscore the need to refactor this field though.

**Comment by huayang-codaio** [comment]
oh so defaultValue is indeed suggestedValue. I just realized it. 

let's close that ticket. the real ticket might be just renaming defaultValue to suggested value.

**Pull request closed without merging**
