### PR TITLE
create 0.4.5 release

### PR DESCRIPTION
**Pull request by huayang-codaio**
I don't seem to have this package in my npm account (huayang@coda.io). @jonathan-codaio can you help publish this?

### CODE REVIEW

**Review by jonathan-codaio — APPROVED** [review]
Sure, will publish now. It looks like Nigel or Oleg should be able to make you a member of the npm org so that you can publish too.

For updating the `packs` repo, you don't actually need a published release since it's just based on the commit, you can make those kinds of changes independently of the release.

**Comment by huayang-codaio** [comment]
yeah, this is for the packs-example repo. I'll ask Nigel / Oleg for npm org access.

**Comment by jonathan-codaio** [comment]
Ok new version is published now.

**Comment by huayang-codaio** [comment]
thanks!

**Pull request merged**
