### PR TITLE
(temporarily) revert pkce commit because of coda linter slowness

### PR DESCRIPTION
**Pull request by huayang-codaio**
this commit somehow causes significant lint slow down in the coda repo. slack thread: https://codaproject.slack.com/archives/C09H9UE4V/p1651796453326759

- right before that commit, coda lint takes 11 mins: https://app.circleci.com/pipelines/github/coda/coda/211168/workflows/978cc7af-5d29-49da-9028-d63be6741009/jobs/1217073
- with that commit, coda lint takes 20+mins: https://app.circleci.com/pipelines/github/coda/coda/211171/workflows/79c686f8-498f-4de9-aefa-9562909e3d96/jobs/1217103
- reverting the commit on packs-sdk, coda lint takes way faster (still running though): https://app.circleci.com/pipelines/github/coda/coda/211180/workflows/8ef03f96-112a-4096-8fed-9a609226bdf4/jobs/1217183

I need to do further investigation but this should unblock bumping packs-sdk in coda.

### CODE REVIEW

**Review by jonathan-codaio — APPROVED** [review]

**Comment by spencer-codaio** [comment]
> reverting the commit on packs-sdk, coda lint takes way faster (still running though): [app.circleci.com/pipelines/github/coda/coda/211180/workflows/8ef03f96-112a-4096-8fed-9a609226bdf4/jobs/1217183](https://app.circleci.com/pipelines/github/coda/coda/211180/workflows/8ef03f96-112a-4096-8fed-9a609226bdf4/jobs/1217183)

err is this taking faster? it looks like it's already been running 16 miins?

**Review by steve-codaio — APPROVED** [review]

**Comment by huayang-codaio** [comment]
@spencer-codaio only look at the "lint all files" step

**Review by spencer-codaio — APPROVED** [review]

**Review by spencer-codaio — COMMENTED** [review]
how strange this commit is so small.. 

thanks for digging into this and bisecting!!!

**Comment by huayang-codaio** [comment]
yeah, I have no clue. this change is small but somehow is affecting tons of unrelated file linting in coda repo..

**Pull request merged**
