### PR TITLE
Validate the result array for sync tables, not the entire result object

### PR DESCRIPTION
**Pull request by patrick-codaio**

### CODE REVIEW

**Review by huayang-codaio — APPROVED** [review]
ah good catch. thanks!

**Comment by huayang-codaio** [comment]
I guess this needs a new version to be published. can you add 0.4.6?

**Review by al-codaio — APPROVED** [review]
lgtm

**Comment by patrick-codaio** [comment]
Confirming: I made 0.4.6 in this PR.

**Pull request merged**
