### PR TITLE
Update dependency pascalcase to v2

### PR DESCRIPTION
**Pull request by krypton-build-user**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [pascalcase](https://togithub.com/jonschlinkert/pascalcase) | dependencies | major | [`1.0.0` -> `2.0.0`](https://renovatebot.com/diffs/npm/pascalcase/1.0.0/2.0.0) |

---

### Release Notes

<details>
<summary>jonschlinkert/pascalcase</summary>

### [`v2.0.0`](https://togithub.com/jonschlinkert/pascalcase/compare/1.0.0...2.0.0)

[Compare Source](https://togithub.com/jonschlinkert/pascalcase/compare/1.0.0...2.0.0)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Self-Hosted Renovate Bot](https://togithub.com/coda/renovate-config). Find all logs [here](https://app.circleci.com/pipelines/github/coda/renovate-config?branch=main).

### CODE REVIEW

**Comment by krypton-build-user** [comment]
### ⚠ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you click the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: yarn.lock

```
You don't have permission to create /tmp/renovate/cache/containerbase.
curl: (23) Failed writing received data to disk/application
Download failed: https://nodejs.org/dist/v18.14.2/SHASUMS256.txt

```

**Comment by dweitzman-codaio** [comment]
This can be test case for https://github.com/coda/packs-sdk/pull/2478

This PR would need to rebuild the thunk. Ideally we can make renovate do that automatically

**Comment by jonathan-codaio** [comment]
@dweitzman-codaio I think bumping this breaks the way we normalize column names, this was a longstanding issue that we finally understood better recently: https://codaproject.slack.com/archives/C02K6EABVMK/p1673551144680909

I thought there was a test that would catch this and that we maybe had the version pinned on yarn or told dependabot to ignore this version, we may need to do the same for Renovate.

**Comment by dweitzman-codaio** [comment]
The test may be working. This PR didn't get as far as running the tests because of the frozen lockfile pr earlier today

I have a fix pending review for renovate so it will update the lockfile

**Comment by dweitzman-codaio** [comment]
My attempt to get renovate to update the generated files didn't work. I'm not going to look into this more for now, so closing the PR

**Comment by krypton-build-user** [comment]
### Renovate Ignore Notification

As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future 2.x releases. However, if you upgrade to 2.x manually then Renovate will reenable minor and patch updates automatically.

If this PR was closed by mistake or you changed your mind, you can simply rename this PR and you will soon get a fresh replacement PR opened.

**Pull request closed without merging**
