### PR TITLE
Link to specific commit hashes from reference documentation

### PR DESCRIPTION
**Pull request by dweitzman-codaio**
This is defense against the documentation links getting out-of-date every time
the types get updated in code.

Not 100% sure how to test this with circleci, but I tested the command locally

Testing:

Built with circleci on a devbox (mac OS was having a docker issue) and also changed the build command to this because I wasn't seeing output files saved anywhere on local disk:
```
DOC_GIT_REVISION="$(git rev-parse HEAD)" make docs && grep types.ts docs/reference/sdk/types/SystemAuthentication.md
```

This output printed shows that the new code is working (the commit hash is from this PR):
```
[types.ts:636](https://github.com/coda/packs-sdk/blob/e31687b1ca6b8940422948d7c1ddbf83b4f91ebd/types.ts#L636)
```

### CODE REVIEW

**Comment by dweitzman-codaio** [comment]
Not sure if we'd want to do this or not, but figured it was worth a discussion

**Comment by ekoleda-codaio** [comment]
Seems reasonable to me. There are instructions for local testing [here](https://circleci.com/docs/2.0/local-cli/). I ran into [this issue](https://github.com/CircleCI-Public/circleci-cli/issues/672#issuecomment-1062696042) when trying to use it though.

**Comment by dweitzman-codaio** [comment]
I was able to test this, kinda sorta, and it did catch a typo. Updated the description

**Review by spencer-codaio — APPROVED** [review]
this is great! Sounds great to me if the testing of it works. this should also better support the case if we ever want to expose documentation for previous SDK versions from the latest (which we support hosting-wise just havent exposed publicly)

**Review by jonathan-codaio — COMMENTED** [review]
Is it expected that the staged readthedocs site for this PR doesn't seem to reflect the changes? https://coda-packs-sdk--1919.com.readthedocs.build/en/1919/reference/sdk/ has links without commit hashes.

**Comment by dweitzman-codaio** [comment]
> Is it expected that the staged readthedocs site for this PR doesn't seem to reflect the changes? [coda-packs-sdk--1919.com.readthedocs.build/en/1919/reference/sdk](https://coda-packs-sdk--1919.com.readthedocs.build/en/1919/reference/sdk/) has links without commit hashes.

What configures this readthedocs build for PRs? I can't find anything about `readthedocs` in the repo, and it doesn't seem like circleci is involved in deploying them

**Comment by ekoleda-codaio** [comment]
> What configures this readthedocs build for PRs?

It runs the mkdocs tool on it's own, using the `mkdocs.yml` config file and markdown files present in `/docs`. In this case the markdown files generated by `typedoc` are pointing to main, since the Makefile falls back to main when not explicitly specified.

**Comment by dweitzman-codaio** [comment]
Anyone have concerns about PR `readthedocs` links still going to `main` even though circleci builds wouldn't like to specific commit hashes (and/or ideas for how to make the `readthedocs` links aware of commit hashes)?

**Comment by ekoleda-codaio** [comment]
I think it's fine. We only use readthedocs for previews of PRs, so it's not something a normal reader would see. Maybe we can figure out something more sophisticated in the future.

**Review by jonathan-codaio — APPROVED** [review]
That's ok with me. It's a good quirk for people to be aware of though.

**Comment by dweitzman-codaio** [comment]
Documentation links generated by circleci now seem to be working as expected, but I haven't deployed docs to prod since I think we're holding off on documentation releases until 0.11.0 gets tagged

**Comment by spencer-codaio** [comment]
> Documentation links generated by circleci now seem to be working as expected, but I haven't deployed docs to prod since I think we're holding off on documentation releases until 0.11.0 gets tagged

great! yup we can hold off on that until we actually releas

**Pull request merged**
