### PR TITLE
add a note for oauth providers only taking comma-separated scopes

### PR DESCRIPTION
**Pull request by huayang-codaio**
Caught today debugging the strava pack. 

This is not a fix but just adding a note before we want to decide if this is ever going to be fixed.

### CODE REVIEW

**Review by jonathan-codaio — COMMENTED** [review]
This makes sense, but given that we track OAuth scopes as structured data in the DB now, this would break that tracking if we advised people to do this. So I'm not sure we want to endorse this workaround more broadly, behind internal use on the adhoc.

Would it be possible to fix this by adding an optional delimeter setting on the oauth def in the manifest? (Not saying it's a priority to do this)

FYI @patrick-codaio

**Comment by huayang-codaio** [comment]
we definitely can if it's necessary to do so. there might be a few places to check & fix. 

so far I only saw one oauth provider not accepting the standard scopes protocol.

**Comment by patrick-codaio** [comment]
Thanks for the heads up.

**Comment by huayang-codaio** [comment]
let me close this one and add it to the bug list I guess.

**Pull request closed without merging**
