### PR TITLE
add automated flow for publishing to npm when push to release

### PR DESCRIPTION
**Pull request by spencer-codaio**
any concerns with this approach? wanted to get this in to test with releasing the new version

### CODE REVIEW

**Review by jonathan-codaio — COMMENTED** [review]
Ah, so the idea is that when we update the `release` branch it'll update the docs and npm together? That seems reasonable.

The snag is authenticating with npm. What's the role user that would do this, and are credentials set up for that? Probably solvable problems, except currently our npm settings require an OTP code for publishing a new package. We could talk about relaxing that, or see if there's a way to provide that in the approval step.

**Comment by spencer-codaio** [comment]
yep! thats the idea so that they're kept in sync.

ahh okay will keep this on the burner then and can see if i figure out a way after doing the manual release. OTP seems difficult to handle...

**Comment by jonathan-codaio** [comment]
> yep! thats the idea so that they're kept in sync.
> 
> ahh okay will keep this on the burner then and can see if i figure out a way after doing the manual release. OTP seems difficult to handle...

We can choose to relax it, just have to put some thought into what the risks are.

Though given that this is an open-source repo, we may want a sanity-check on what gets published to npm rather than blindly auto publishing the contents of the `release` branch in case somebody finds a way to attack that.

**Comment by spencer-codaio** [comment]
hmm yeah seems like more overhead than worth right now -- maybe after deploy it just sends you a slack message reminding you to publish to NPM or something like that. Will close for now

**Pull request closed without merging**
