### PR TITLE
testing using github action to autu-merge dependabot PRs for minor changes

### PR DESCRIPTION
**Pull request by huayang-codaio**
Just found this particular github action that auto approves & merge dependabot PRs. 

The setup is to run it hourly for now (simply because it allows the dependabot to rebase after conflicts). Let's see if it works.

### CODE REVIEW

**Comment by huayang-codaio** [comment]
I have no way to test this right now since there's no pending dependabot PRs. I'll wait for the coming Tuesday to work with the next eng merging PRs..

**Review by jonathan-codaio — APPROVED** [review]
Cool! @nigel-codaio @gita-codaio Any objections to us kicking the tires on this on the packs-sdk repo?

**Comment by nigel-codaio** [comment]
I'm not sure it meets our compliance requirements that all code needs to be approved by an engineer. @chris-codaio WDYT?

**Comment by chris-codaio** [comment]
I think you're right Nigel.  This would seem to violate our policy.

**Comment by huayang-codaio** [comment]
Got it. We will not do the auto merge then. It’s just attractive idea to
avoid the time spent on merging the dependabot PRs.

**Pull request closed without merging**
