### PR TITLE
Bump version to 0.12.0

### PR DESCRIPTION
**Pull request by alexd-codaio**
@jonathan-codaio @coda/packs PTAL

Looks good?

### CODE REVIEW

**Review by jonathan-codaio — COMMENTED** [review]
Mind updating the CHANGELOG too, replacing `[Unreleased]` with `[0.12.0]`

**Comment by jonathan-codaio** [comment]
Not sure what the CI failure is about, maybe other local changes not in the PR?

**Comment by alexd-codaio** [comment]
> Mind updating the CHANGELOG too, replacing `[Unreleased]` with `[0.12.0]`

Done.

> Not sure what the CI failure is about, maybe other local changes not in the PR?

Forgot to `make bs` I think? Dunno.

**Review by huayang-codaio — APPROVED** [review]
lgtm. 

cc @spencer-codaio your change is going in with 0.12.0

**Review by jonathan-codaio — APPROVED** [review]

**Pull request merged**
