### PR TITLE
Update dependency @types/yargs to v17.0.22

### PR DESCRIPTION
**Pull request by krypton-build-user**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@types/yargs](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yargs) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | patch | [`17.0.19` -> `17.0.22`](https://renovatebot.com/diffs/npm/@types%2fyargs/17.0.19/17.0.22) |

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Self-Hosted Renovate Bot](https://togithub.com/coda/renovate-config). Find all logs [here](https://app.circleci.com/pipelines/github/coda/renovate-config?branch=main).

### CODE REVIEW

**Comment by dweitzman-codaio** [comment]
Seems like this yarns typing PR upstream causes the breakage here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63694

Specifically this part:

Old type:
```
command<U>(module: CommandModule<T, U>): Argv<U>;
```

New type:
```
command(module: CommandModule<T, any>): Argv<T>;
```

Not sure exactly what the story is here, but it might be possible to fix it by using ordered parameters instead of the CommandModule type

**Comment by dweitzman-codaio** [comment]
Seems like the breakage here may not be a regression in typing as much as it may be revealing that type safety was probably never is present as it appeared before: you could have always passed completely the wrong handler to the "handler" argument without getting a type error.

Seems like putting "as any" casts into the code is at least a more honest way to indicate that.

**Comment by dweitzman-codaio** [comment]
cc @jonathan-codaio for unclean dep upgrade

**Review by jonathan-codaio — APPROVED** [review]
Ah ok, yeah I guess this is fine. Seems like on the old version the `handler` type was inferred as `(args: ArgumentsCamelCase<unknown>)` but that was heavily obfuscated. So this is equivalent. Seems valuable to get the strong typing to actually work, but that kind of seems like a yargs bug that inference isn't happening. Do their docs indicate that they expect you to manually do typing in `.command<{something}>(...)`?

**Comment by dweitzman-codaio** [comment]
> Ah ok, yeah I guess this is fine. Seems like on the old version the `handler` type was inferred as `(args: ArgumentsCamelCase<unknown>)` but that was heavily obfuscated. So this is equivalent. Seems valuable to get the strong typing to actually work, but that kind of seems like a yargs bug that inference isn't happening. Do their docs indicate that they expect you to manually do typing in `.command<{something}>(...)`?

yargs itself isn't in typescript

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yargs/yargs-tests.ts shows some examples of what the `@types` folks thing works but nothing there jumps out at me as testing type inference for `.command()`

**Comment by jonathan-codaio** [comment]
Oh ok, yeah that totally makes sense if the types are just from DefinitelyTyped. Would take some restructuring of the JS most likely in conjunction with TS to make inference work properly. We could manually provide the templated type, e.g. `.command<ExecuteArgs>(...)` though. I don't that brings any new type safety but I guess at least expresses the intent of the command definition.

**Comment by krypton-build-user** [comment]
### Edited/Blocked Notification

Renovate will not automatically rebase this PR, because it does not recognize the last commit author and assumes somebody else may have edited the PR.
You can manually request rebase by checking the rebase/retry box above.

 ⚠ **Warning**: custom changes will be lost.

**Comment by dweitzman-codaio** [comment]
> Oh ok, yeah that totally makes sense if the types are just from DefinitelyTyped. Would take some restructuring of the JS most likely in conjunction with TS to make inference work properly. We could manually provide the templated type, e.g. `.command<ExecuteArgs>(...)` though. I don't that brings any new type safety but I guess at least expresses the intent of the command definition.

The `.command()` method doesn't type parameters, so something like this is possible but it seems like it might involve having a named variable for each command like `const executeCommand: yargs.CommandModule<{}, ExecuteArgs> = {...}` and then `.command(executeCommand)`

One option here might be to move all the command declarations into their respective implementation files. That might make it a little more awkward to share common arguments or default values, though.

My inclination is to merge this as-in with the "as any" since it seems like the alternatives involve more thinking and refactoring that don't seem important right now.

**Comment by jonathan-codaio** [comment]
Ok let's merge this as-is.

It turns out it is doing strong typing and type inference, but it's just doing it naively and in a way that's not really compatible with how yargs actually works.

This new package version seems to be much better at type inference than the old version, and it is indeed inferring a type for `handler` based on the inputs to `builder`. The problem is, the arguments passed to the handler also include positional parameters that are given names in the command string: for example, in the command definition `'execute <manifestPath> <formulaName>'`, there are arguments called `manifestPath` and `formulaName` in addition to the named arguments like `fetch` and `vm`. The handler correctly declares that it accepts parameters named `manifestPath` and `formulaName`. But the inferred type of `handler` is _not_ expecting those parameters, because they are invisible to the type system because those names only exist inside of an arbitrary command string. And the typing is naively implemented because instead of allowing the handler to accept _at least_ the named types from `builder` it seems to require that the handler accept _only_ the named types from `builder`. This is probably beyond our ability to control without fixing their type defs.

**Pull request merged**
