### PR TITLE
More specific typing for PropertyOptionsExecutionContext.propertySchema

### PR DESCRIPTION
**Pull request by dweitzman-codaio**
Adjusting the typing here allows packs to read "fromKey" without any typescript casts.

### CODE REVIEW

**Review by huayang-codaio — APPROVED** [review]

**Comment by patrick-codaio** [comment]
LGTM, though I'm no typescript expert.

**Comment by dweitzman-codaio** [comment]
I'm not sure how best to resolve the typedoc validation issue here. CI is correct that `CodaInternalRichTextSchema` is not a documented type.

The hidden rich text type is actually already mentioned in the `StringSchema` type reference doc, which somehow hasn't triggered this test failure.

I think I'll leave this PR alone until Eric is back and I may merge a typecast in another repo in the meantime with a TODO to clean it up after some version of this PR is merged

**Review by jonathan-codaio — COMMENTED** [review]
Can you try adding that token in `intentionallyNotExported` in `typedoc.js`? I think that powers exemptions from this check.

**Comment by dweitzman-codaio** [comment]
> Can you try adding that token in `intentionallyNotExported` in `typedoc.js`? I think that powers exemptions from this check.

Seems like `intentionallyNotExported` still prints a warning since the types are exported, just not documented, and printing any warning is enough to make the test mad

**Comment by dweitzman-codaio** [comment]
Rebased this and the typedoc problem seems to have mysteriously gone away. Now the documentation just gives the type of `propertyOptions` as `object` rather than a giant list of all the union types it could contain, avoiding references to `@hidden` internal types.

I don't know why the behavior is different now -- maybe a dependency upgrade?

I've also added an explicit `{@link Schema}` to help people who are browsing around and want to find the relevant typedoc for the field.

**Pull request merged**
